name: build

on:
  push:
    branches:
      - main
      - dev*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.2', '3.3', '3.4']
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build and test
        run: bundle exec rake compile test

  build-debug:
    name: Ruby debug
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby head debug
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: debug
      - name: Build and Install
        run: |
          gem build numo-narray-alt.gemspec
          gem install numo-narray-alt-*.gem
          bundle install
      - name: Tests
        run: rake test

  build-rocky:
    runs-on: ubuntu-latest
    name: Ruby 3.3 (Rocky)
    container: rockylinux/rockylinux:9
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby
        run: |
          dnf update -y
          dnf module -y enable ruby:3.3
          dnf install -y gcc make git ruby-devel ruby
          bundle config silence_root_warning true
          bundle install
      - name: Build and test
        run: |
          bundle exec rake

  build-win:
    runs-on: windows-latest
    name: Ruby 3.4 (Windows)
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - name: Build and test
        run: bundle exec rake compile test

  build-mac:
    runs-on: macos-latest
    name: Ruby 3.4 (macOS)
    steps:
      - uses: actions/checkout@v5
      - name: Set up Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - name: Build and test
        run: bundle exec rake compile test
